/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutomationBuilderRouteImport } from './routes/automation-builder'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ToolsWordToPdfRouteImport } from './routes/tools/word-to-pdf'
import { Route as ToolsSplitPdfRouteImport } from './routes/tools/split-pdf'
import { Route as ToolsPdfToWordRouteImport } from './routes/tools/pdf-to-word'
import { Route as ToolsPdfToJpgRouteImport } from './routes/tools/pdf-to-jpg'
import { Route as ToolsOcrPdfRouteImport } from './routes/tools/ocr-pdf'
import { Route as ToolsMergePdfRouteImport } from './routes/tools/merge-pdf'
import { Route as ToolsJpgToPdfRouteImport } from './routes/tools/jpg-to-pdf'
import { Route as ToolsCompressPdfRouteImport } from './routes/tools/compress-pdf'
import { Route as ToolsAiChatRouteImport } from './routes/tools/ai-chat'
import { Route as DocumentFileIdRouteImport } from './routes/document/$fileId'
import { Route as DashboardWorkflowsRouteImport } from './routes/dashboard/workflows'
import { Route as DashboardFilesRouteImport } from './routes/dashboard/files'
import { Route as AiSummarizePdfRouteImport } from './routes/ai/summarize-pdf'
import { Route as AiExtractDataRouteImport } from './routes/ai/extract-data'
import { Route as AiChatWithPdfRouteImport } from './routes/ai/chat-with-pdf'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationBuilderRoute = AutomationBuilderRouteImport.update({
  id: '/automation-builder',
  path: '/automation-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ToolsWordToPdfRoute = ToolsWordToPdfRouteImport.update({
  id: '/tools/word-to-pdf',
  path: '/tools/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSplitPdfRoute = ToolsSplitPdfRouteImport.update({
  id: '/tools/split-pdf',
  path: '/tools/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfToWordRoute = ToolsPdfToWordRouteImport.update({
  id: '/tools/pdf-to-word',
  path: '/tools/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfToJpgRoute = ToolsPdfToJpgRouteImport.update({
  id: '/tools/pdf-to-jpg',
  path: '/tools/pdf-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOcrPdfRoute = ToolsOcrPdfRouteImport.update({
  id: '/tools/ocr-pdf',
  path: '/tools/ocr-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMergePdfRoute = ToolsMergePdfRouteImport.update({
  id: '/tools/merge-pdf',
  path: '/tools/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJpgToPdfRoute = ToolsJpgToPdfRouteImport.update({
  id: '/tools/jpg-to-pdf',
  path: '/tools/jpg-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompressPdfRoute = ToolsCompressPdfRouteImport.update({
  id: '/tools/compress-pdf',
  path: '/tools/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAiChatRoute = ToolsAiChatRouteImport.update({
  id: '/tools/ai-chat',
  path: '/tools/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentFileIdRoute = DocumentFileIdRouteImport.update({
  id: '/document/$fileId',
  path: '/document/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowsRoute = DashboardWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardRoute,
} as any)
const AiSummarizePdfRoute = AiSummarizePdfRouteImport.update({
  id: '/ai/summarize-pdf',
  path: '/ai/summarize-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AiExtractDataRoute = AiExtractDataRouteImport.update({
  id: '/ai/extract-data',
  path: '/ai/extract-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatWithPdfRoute = AiChatWithPdfRouteImport.update({
  id: '/ai/chat-with-pdf',
  path: '/ai/chat-with-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/automation-builder': typeof AutomationBuilderRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/files': typeof FilesRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/ai/chat-with-pdf': typeof AiChatWithPdfRoute
  '/ai/extract-data': typeof AiExtractDataRoute
  '/ai/summarize-pdf': typeof AiSummarizePdfRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/document/$fileId': typeof DocumentFileIdRoute
  '/tools/ai-chat': typeof ToolsAiChatRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/ocr-pdf': typeof ToolsOcrPdfRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/split-pdf': typeof ToolsSplitPdfRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/automation-builder': typeof AutomationBuilderRoute
  '/files': typeof FilesRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/ai/chat-with-pdf': typeof AiChatWithPdfRoute
  '/ai/extract-data': typeof AiExtractDataRoute
  '/ai/summarize-pdf': typeof AiSummarizePdfRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/document/$fileId': typeof DocumentFileIdRoute
  '/tools/ai-chat': typeof ToolsAiChatRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/ocr-pdf': typeof ToolsOcrPdfRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/split-pdf': typeof ToolsSplitPdfRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/dashboard': typeof DashboardIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/automation-builder': typeof AutomationBuilderRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/files': typeof FilesRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/ai/chat-with-pdf': typeof AiChatWithPdfRoute
  '/ai/extract-data': typeof AiExtractDataRoute
  '/ai/summarize-pdf': typeof AiSummarizePdfRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/document/$fileId': typeof DocumentFileIdRoute
  '/tools/ai-chat': typeof ToolsAiChatRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/ocr-pdf': typeof ToolsOcrPdfRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/split-pdf': typeof ToolsSplitPdfRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/automation-builder'
    | '/dashboard'
    | '/files'
    | '/pricing'
    | '/settings'
    | '/ai/chat-with-pdf'
    | '/ai/extract-data'
    | '/ai/summarize-pdf'
    | '/dashboard/files'
    | '/dashboard/workflows'
    | '/document/$fileId'
    | '/tools/ai-chat'
    | '/tools/compress-pdf'
    | '/tools/jpg-to-pdf'
    | '/tools/merge-pdf'
    | '/tools/ocr-pdf'
    | '/tools/pdf-to-jpg'
    | '/tools/pdf-to-word'
    | '/tools/split-pdf'
    | '/tools/word-to-pdf'
    | '/dashboard/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/automation-builder'
    | '/files'
    | '/pricing'
    | '/settings'
    | '/ai/chat-with-pdf'
    | '/ai/extract-data'
    | '/ai/summarize-pdf'
    | '/dashboard/files'
    | '/dashboard/workflows'
    | '/document/$fileId'
    | '/tools/ai-chat'
    | '/tools/compress-pdf'
    | '/tools/jpg-to-pdf'
    | '/tools/merge-pdf'
    | '/tools/ocr-pdf'
    | '/tools/pdf-to-jpg'
    | '/tools/pdf-to-word'
    | '/tools/split-pdf'
    | '/tools/word-to-pdf'
    | '/dashboard'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/automation-builder'
    | '/dashboard'
    | '/files'
    | '/pricing'
    | '/settings'
    | '/ai/chat-with-pdf'
    | '/ai/extract-data'
    | '/ai/summarize-pdf'
    | '/dashboard/files'
    | '/dashboard/workflows'
    | '/document/$fileId'
    | '/tools/ai-chat'
    | '/tools/compress-pdf'
    | '/tools/jpg-to-pdf'
    | '/tools/merge-pdf'
    | '/tools/ocr-pdf'
    | '/tools/pdf-to-jpg'
    | '/tools/pdf-to-word'
    | '/tools/split-pdf'
    | '/tools/word-to-pdf'
    | '/dashboard/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  AutomationBuilderRoute: typeof AutomationBuilderRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FilesRoute: typeof FilesRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  AiChatWithPdfRoute: typeof AiChatWithPdfRoute
  AiExtractDataRoute: typeof AiExtractDataRoute
  AiSummarizePdfRoute: typeof AiSummarizePdfRoute
  DocumentFileIdRoute: typeof DocumentFileIdRoute
  ToolsAiChatRoute: typeof ToolsAiChatRoute
  ToolsCompressPdfRoute: typeof ToolsCompressPdfRoute
  ToolsJpgToPdfRoute: typeof ToolsJpgToPdfRoute
  ToolsMergePdfRoute: typeof ToolsMergePdfRoute
  ToolsOcrPdfRoute: typeof ToolsOcrPdfRoute
  ToolsPdfToJpgRoute: typeof ToolsPdfToJpgRoute
  ToolsPdfToWordRoute: typeof ToolsPdfToWordRoute
  ToolsSplitPdfRoute: typeof ToolsSplitPdfRoute
  ToolsWordToPdfRoute: typeof ToolsWordToPdfRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-builder': {
      id: '/automation-builder'
      path: '/automation-builder'
      fullPath: '/automation-builder'
      preLoaderRoute: typeof AutomationBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/tools/word-to-pdf': {
      id: '/tools/word-to-pdf'
      path: '/tools/word-to-pdf'
      fullPath: '/tools/word-to-pdf'
      preLoaderRoute: typeof ToolsWordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/split-pdf': {
      id: '/tools/split-pdf'
      path: '/tools/split-pdf'
      fullPath: '/tools/split-pdf'
      preLoaderRoute: typeof ToolsSplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-to-word': {
      id: '/tools/pdf-to-word'
      path: '/tools/pdf-to-word'
      fullPath: '/tools/pdf-to-word'
      preLoaderRoute: typeof ToolsPdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-to-jpg': {
      id: '/tools/pdf-to-jpg'
      path: '/tools/pdf-to-jpg'
      fullPath: '/tools/pdf-to-jpg'
      preLoaderRoute: typeof ToolsPdfToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ocr-pdf': {
      id: '/tools/ocr-pdf'
      path: '/tools/ocr-pdf'
      fullPath: '/tools/ocr-pdf'
      preLoaderRoute: typeof ToolsOcrPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/merge-pdf': {
      id: '/tools/merge-pdf'
      path: '/tools/merge-pdf'
      fullPath: '/tools/merge-pdf'
      preLoaderRoute: typeof ToolsMergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/jpg-to-pdf': {
      id: '/tools/jpg-to-pdf'
      path: '/tools/jpg-to-pdf'
      fullPath: '/tools/jpg-to-pdf'
      preLoaderRoute: typeof ToolsJpgToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compress-pdf': {
      id: '/tools/compress-pdf'
      path: '/tools/compress-pdf'
      fullPath: '/tools/compress-pdf'
      preLoaderRoute: typeof ToolsCompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ai-chat': {
      id: '/tools/ai-chat'
      path: '/tools/ai-chat'
      fullPath: '/tools/ai-chat'
      preLoaderRoute: typeof ToolsAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$fileId': {
      id: '/document/$fileId'
      path: '/document/$fileId'
      fullPath: '/document/$fileId'
      preLoaderRoute: typeof DocumentFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflows': {
      id: '/dashboard/workflows'
      path: '/workflows'
      fullPath: '/dashboard/workflows'
      preLoaderRoute: typeof DashboardWorkflowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/files': {
      id: '/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/ai/summarize-pdf': {
      id: '/ai/summarize-pdf'
      path: '/ai/summarize-pdf'
      fullPath: '/ai/summarize-pdf'
      preLoaderRoute: typeof AiSummarizePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/extract-data': {
      id: '/ai/extract-data'
      path: '/ai/extract-data'
      fullPath: '/ai/extract-data'
      preLoaderRoute: typeof AiExtractDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/chat-with-pdf': {
      id: '/ai/chat-with-pdf'
      path: '/ai/chat-with-pdf'
      fullPath: '/ai/chat-with-pdf'
      preLoaderRoute: typeof AiChatWithPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardWorkflowsRoute: typeof DashboardWorkflowsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardWorkflowsRoute: DashboardWorkflowsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  AutomationBuilderRoute: AutomationBuilderRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FilesRoute: FilesRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  AiChatWithPdfRoute: AiChatWithPdfRoute,
  AiExtractDataRoute: AiExtractDataRoute,
  AiSummarizePdfRoute: AiSummarizePdfRoute,
  DocumentFileIdRoute: DocumentFileIdRoute,
  ToolsAiChatRoute: ToolsAiChatRoute,
  ToolsCompressPdfRoute: ToolsCompressPdfRoute,
  ToolsJpgToPdfRoute: ToolsJpgToPdfRoute,
  ToolsMergePdfRoute: ToolsMergePdfRoute,
  ToolsOcrPdfRoute: ToolsOcrPdfRoute,
  ToolsPdfToJpgRoute: ToolsPdfToJpgRoute,
  ToolsPdfToWordRoute: ToolsPdfToWordRoute,
  ToolsSplitPdfRoute: ToolsSplitPdfRoute,
  ToolsWordToPdfRoute: ToolsWordToPdfRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
